"""Unit tests untuk Ollama Generator — BaseGeneratorProvider, routing, fallback."""

import pytest
from unittest.mock import AsyncMock, MagicMock

from app.ai.base_generator import BaseGeneratorProvider
from app.ai.ollama_generator_provider import OllamaGeneratorProvider
from app.utils.errors import NoProviderAvailableError


# ─── Fixtures ───────────────────────────────────────────────────────────

@pytest.fixture
def mock_settings():
    settings = MagicMock()
    settings.ollama_base_url = "http://localhost:11434"
    settings.ollama_chat_model = "qwen2.5:7b-instruct"
    settings.ollama_tor_model = "qwen2.5:7b-instruct"
    settings.ollama_tor_temperature = 0.3
    settings.ollama_num_ctx = 4096
    settings.ollama_tor_timeout = 120
    return settings


@pytest.fixture
def mock_gemini_provider():
    from app.models.generate import GeminiResponse

    provider = AsyncMock(spec=BaseGeneratorProvider)
    provider.provider_name = "gemini"
    provider.model_name = "gemini-2.0-flash"
    provider.is_available.return_value = True

    async def mock_generate(prompt):
        return GeminiResponse(
            text="# TOR Test\nGenerated by Gemini.",
            prompt_tokens=50,
            completion_tokens=100,
            duration_ms=1500,
        )

    async def mock_generate_stream(prompt):
        yield "# TOR Test\n"
        yield "Generated by Gemini."

    provider.generate = mock_generate
    provider.generate_stream = mock_generate_stream
    return provider


@pytest.fixture
def mock_ollama_provider():
    provider = AsyncMock(spec=BaseGeneratorProvider)
    provider.provider_name = "ollama"
    provider.model = "qwen2.5:7b-instruct"
    provider.is_available.return_value = True

    async def mock_generate(prompt):
        return "# TOR Test\nGenerated by Ollama."

    async def mock_generate_stream(prompt):
        yield "# TOR Test\n"
        yield "Generated by Ollama."

    provider.generate = mock_generate
    provider.generate_stream = mock_generate_stream
    return provider


@pytest.fixture
def mock_session_mgr():
    mgr = AsyncMock()
    session = AsyncMock()
    session.id = "test-session-1"
    session.state = "CHATTING"
    session.completeness_score = 0.85
    session.extracted_data = MagicMock()
    session.extracted_data.judul = "Test Kegiatan"
    session.extracted_data.missing_fields.return_value = []
    session.extracted_data.filled_fields.return_value = ["judul", "latar_belakang"]
    session.gemini_calls_count = 0
    session.total_tokens_gemini = 0
    mgr.get.return_value = session
    mgr.get_chat_history.return_value = []
    return mgr


@pytest.fixture
def generate_service(mock_gemini_provider, mock_ollama_provider, mock_session_mgr):
    """Buat GenerateService dengan mock providers."""
    from app.services.generate_service import GenerateService

    # Mock cache — return None (no cache)
    mock_cache = AsyncMock()
    mock_cache.get.return_value = None

    # Mock cost_ctrl
    mock_cost_ctrl = AsyncMock()

    service = GenerateService(
        gemini_provider=mock_gemini_provider,
        ollama_provider=mock_ollama_provider,
        session_mgr=mock_session_mgr,
        rag_pipeline=None,
        gemini_prompt_builder=MagicMock(),
        ollama_prompt_builder=MagicMock(),
        post_processor=MagicMock(),
        cache=mock_cache,
        cost_ctrl=mock_cost_ctrl,
        style_manager=MagicMock(),
    )
    # Mock prompt builders
    service.prompt_builders["gemini"].build_standard.return_value = "gemini prompt"
    service.prompt_builders["ollama"].build_standard.return_value = "ollama prompt"
    service.prompt_builders["gemini"].build_escalation.return_value = "gemini escalation prompt"
    service.prompt_builders["ollama"].build_escalation.return_value = "ollama escalation prompt"

    # Mock post_processor
    from app.models.generate import ProcessedTOR
    service.post_processor.process.return_value = ProcessedTOR(
        content="# TOR Test\nGenerated content.",
        word_count=10,
        has_assumptions=False,
    )

    # Mock style_manager
    style = MagicMock()
    style.to_prompt_spec.return_value = "format spec"
    service.style_manager.get_active_style.return_value = style

    return service


# ─── Test 1: BaseGeneratorProvider Interface ───────────────────────────

class TestBaseGeneratorProvider:
    """Pastikan abstract class tidak bisa di-instantiate langsung."""

    def test_cannot_instantiate_abstract(self):
        """BaseGeneratorProvider tidak bisa dibuat langsung."""
        with pytest.raises(TypeError):
            BaseGeneratorProvider()  # type: ignore

    def test_gemini_implements_interface(self, mock_gemini_provider):
        """GeminiProvider mengimplementasi BaseGeneratorProvider."""
        assert isinstance(mock_gemini_provider, BaseGeneratorProvider)
        assert mock_gemini_provider.provider_name == "gemini"

    def test_ollama_implements_interface(self, mock_ollama_provider):
        """OllamaGeneratorProvider mengimplementasi BaseGeneratorProvider."""
        assert isinstance(mock_ollama_provider, BaseGeneratorProvider)
        assert mock_ollama_provider.provider_name == "ollama"


# ─── Test 2: OllamaGeneratorProvider Initialization ────────────────────

class TestOllamaGeneratorInit:
    """Test inisialisasi OllamaGeneratorProvider."""

    def test_init_with_tor_model(self, mocker, mock_settings):
        """Menggunakan ollama_tor_model jika diset."""
        mock_settings.ollama_tor_model = "llama3:8b"
        mocker.patch("ollama.AsyncClient")
        provider = OllamaGeneratorProvider(mock_settings)
        assert provider.model == "llama3:8b"

    def test_init_fallback_to_chat_model(self, mocker, mock_settings):
        """Fallback ke ollama_chat_model jika tor_model kosong."""
        mock_settings.ollama_tor_model = ""
        mocker.patch("ollama.AsyncClient")
        provider = OllamaGeneratorProvider(mock_settings)
        assert provider.model == mock_settings.ollama_chat_model

    def test_provider_name(self, mocker, mock_settings):
        """Provider name harus 'ollama'."""
        mocker.patch("ollama.AsyncClient")
        provider = OllamaGeneratorProvider(mock_settings)
        assert provider.provider_name == "ollama"


# ─── Test 3: OllamaGeneratorProvider is_available ──────────────────────

class TestOllamaGeneratorAvailable:
    """Test is_available() method."""

    def test_available_when_model_found(self, mocker, mock_settings):
        """True jika model terdaftar di Ollama."""
        mock_client = AsyncMock()
        mock_model = MagicMock()
        mock_model.model = "qwen2.5:7b-instruct"
        mock_client.list.return_value = MagicMock(models=[mock_model])
        mocker.patch("ollama.AsyncClient", return_value=mock_client)

        provider = OllamaGeneratorProvider(mock_settings)
        result = provider.is_available()
        import asyncio
        assert asyncio.run(result) is True

    def test_unavailable_when_model_not_found(self, mocker, mock_settings):
        """False jika model tidak terdaftar."""
        mock_client = AsyncMock()
        mock_client.list.return_value = MagicMock(models=[])
        mocker.patch("ollama.AsyncClient", return_value=mock_client)

        provider = OllamaGeneratorProvider(mock_settings)
        import asyncio
        result = asyncio.run(provider.is_available())
        assert result is False

    def test_unavailable_on_connection_error(self, mocker, mock_settings):
        """False jika Ollama tidak bisa dihubungi."""
        mock_client = AsyncMock()
        mock_client.list.side_effect = ConnectionError("Connection refused")
        mocker.patch("ollama.AsyncClient", return_value=mock_client)

        provider = OllamaGeneratorProvider(mock_settings)
        import asyncio
        result = asyncio.run(provider.is_available())
        assert result is False


# ─── Test 4: GenerateService Provider Resolution ───────────────────────

class TestGenerateServiceResolution:
    """Test _resolve_provider() logic."""

    @pytest.mark.asyncio
    async def test_auto_ollama_when_completeness_high(self, generate_service):
        """Auto mode: completeness >= 0.8 → Ollama."""
        generate_service.session_mgr.get.return_value.completeness_score = 0.85
        generate_service.providers["ollama"].is_available.return_value = True

        result = await generate_service._resolve_provider(
            "session-1", "auto", "standard"
        )
        assert result == "ollama"

    @pytest.mark.asyncio
    async def test_auto_gemini_when_completeness_low(self, generate_service):
        """Auto mode: completeness < 0.8 → Gemini."""
        generate_service.session_mgr.get.return_value.completeness_score = 0.45
        generate_service.providers["gemini"].is_available.return_value = True

        result = await generate_service._resolve_provider(
            "session-1", "auto", "standard"
        )
        assert result == "gemini"

    @pytest.mark.asyncio
    async def test_force_gemini(self, generate_service):
        """Generator='gemini' → pilih Gemini."""
        generate_service.providers["gemini"].is_available.return_value = True

        result = await generate_service._resolve_provider(
            "session-1", "gemini", "standard"
        )
        assert result == "gemini"

    @pytest.mark.asyncio
    async def test_force_ollama(self, generate_service):
        """Generator='ollama' → pilih Ollama."""
        generate_service.providers["ollama"].is_available.return_value = True

        result = await generate_service._resolve_provider(
            "session-1", "ollama", "standard"
        )
        assert result == "ollama"

    @pytest.mark.asyncio
    async def test_fallback_gemini_to_ollama(self, generate_service):
        """Gemini unavailable → fallback ke Ollama."""
        generate_service.providers["gemini"].is_available.return_value = False
        generate_service.providers["ollama"].is_available.return_value = True

        result = await generate_service._resolve_provider(
            "session-1", "gemini", "standard"
        )
        assert result == "ollama"

    @pytest.mark.asyncio
    async def test_fallback_ollama_to_gemini(self, generate_service):
        """Ollama unavailable → fallback ke Gemini."""
        generate_service.providers["ollama"].is_available.return_value = False
        generate_service.providers["gemini"].is_available.return_value = True

        result = await generate_service._resolve_provider(
            "session-1", "ollama", "standard"
        )
        assert result == "gemini"

    @pytest.mark.asyncio
    async def test_no_provider_available(self, generate_service):
        """Semua provider unavailable → raise NoProviderAvailableError."""
        generate_service.providers["gemini"].is_available.return_value = False
        generate_service.providers["ollama"].is_available.return_value = False

        with pytest.raises(NoProviderAvailableError):
            await generate_service._resolve_provider(
                "session-1", "auto", "standard"
            )


# ─── Test 5: GenerateService generate_tor ──────────────────────────────

class TestGenerateServiceGenerate:
    """Test generate_tor() dengan berbagai provider."""

    @pytest.mark.asyncio
    async def test_generate_with_gemini(self, generate_service):
        """Generate TOR via Gemini."""
        generate_service.providers["gemini"].is_available.return_value = True
        generate_service.providers["ollama"].is_available.return_value = False

        result = await generate_service.generate_tor(
            session_id="session-1",
            mode="standard",
            generator="gemini",
        )

        assert result.tor_document is not None
        assert result.tor_document.metadata.generator == "gemini"
        assert result.cached is False

    @pytest.mark.asyncio
    async def test_generate_with_ollama(self, generate_service):
        """Generate TOR via Ollama."""
        generate_service.providers["ollama"].is_available.return_value = True
        generate_service.providers["gemini"].is_available.return_value = False

        result = await generate_service.generate_tor(
            session_id="session-1",
            mode="standard",
            generator="ollama",
        )

        assert result.tor_document is not None
        assert result.tor_document.metadata.generator == "ollama"
        assert result.cached is False

    @pytest.mark.asyncio
    async def test_generate_auto_ollama(self, generate_service):
        """Auto mode dengan completeness tinggi → Ollama."""
        generate_service.session_mgr.get.return_value.completeness_score = 0.85
        generate_service.providers["ollama"].is_available.return_value = True
        generate_service.providers["gemini"].is_available.return_value = True

        result = await generate_service.generate_tor(
            session_id="session-1",
            mode="standard",
            generator="auto",
        )

        assert result.tor_document.metadata.generator == "ollama"

    @pytest.mark.asyncio
    async def test_generate_auto_gemini(self, generate_service):
        """Auto mode dengan completeness rendah → Gemini."""
        generate_service.session_mgr.get.return_value.completeness_score = 0.45
        generate_service.providers["ollama"].is_available.return_value = True
        generate_service.providers["gemini"].is_available.return_value = True

        result = await generate_service.generate_tor(
            session_id="session-1",
            mode="standard",
            generator="auto",
        )

        assert result.tor_document.metadata.generator == "gemini"

    @pytest.mark.asyncio
    async def test_generate_no_provider(self, generate_service):
        """Semua provider unavailable → raise error."""
        generate_service.providers["gemini"].is_available.return_value = False
        generate_service.providers["ollama"].is_available.return_value = False

        with pytest.raises(NoProviderAvailableError):
            await generate_service.generate_tor(
                session_id="session-1",
                mode="standard",
                generator="auto",
            )


# ─── Test 6: NoProviderAvailableError ──────────────────────────────────

class TestNoProviderAvailableError:
    """Test custom error class."""

    def test_error_code(self):
        """Error code harus E013."""
        err = NoProviderAvailableError("test")
        assert err.code == "E013"

    def test_error_message(self):
        """Error message harus informatif."""
        err = NoProviderAvailableError("Ollama down, Gemini down")
        assert "Tidak ada generator" in err.message
        assert err.details == "Ollama down, Gemini down"
